name = "PackageStates"
uuid = "412cc100-f440-45a8-9ec7-153ed5111422"
license = "MIT"
desc = "Package version tracking."
authors = ["Philip Bittihn <philip@bittihn.de>"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
PrettyTables = "1,2"
julia = "1.6"
